[tool.ruff]
line-length = 120
target-version = "py311"

select = ["F", "E", "W", "PL", "B", "I", "ANN"]

ignore = [
    "PLR2004", # Magic variables
]

[tool.ruff.per-file-ignores]
"*.spec" = [
    "F821", # undefined name
    "F841", # assigned but unused
]
