name: Release

on: workflow_dispatch

permissions:
  contents: write

jobs:
  release:
    runs-on: windows-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11.5"

      - name: Read version
        shell: bash
        run: |
          VERSION=$(python -c "import tomllib,pathlib;print(tomllib.loads(pathlib.Path('pyproject.toml').read_text())['project']['version'])")
          echo "VERSION=${VERSION}" >> $GITHUB_ENV

      - name: Create tag
        shell: bash
        run: |
          git tag "${VERSION}"
          git push origin "${VERSION}"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .

      - name: Download libmpv
        run: |
          Invoke-WebRequest -Uri "https://github.com/shinchiro/mpv-winbuild-cmake/releases/download/20260211/mpv-dev-x86_64-v3-20260211-git-3847a81.7z" -OutFile mpv-dev.7z
          7z x mpv-dev.7z -ompv-dev
          Copy-Item mpv-dev/libmpv-2.dll -Destination _internal/

      - name: Build executable
        run: python build.py

      - name: Zip release
        run: Compress-Archive -Path dist/quickplay -DestinationPath dist/quickplay.zip

      - name: Upload release asset
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.VERSION }}
          files: dist/quickplay.zip
